### ISSUE TITLE
include could not find load file: src/liblcb/CMakeLists.txt

### ISSUE THREAD

**Issue by A932756869** [rozhuk-im/msd#1]
-- Performing Test LINKER_FLAG_ZNOEXECSTACK
-- Performing Test LINKER_FLAG_ZNOEXECSTACK - Success
CMake Error at CMakeLists.txt:225 (include):
  include could not find load file:

    src/liblcb/CMakeLists.txt

-- Configuring incomplete, errors occurred!
See also "/root/msd-master/build/CMakeFiles/CMakeOutput.log".
See also "/root/msd-master/build/CMakeFiles/CMakeError.log".

**Comment by A932756869** [comment]
[root@centos7 build]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)

**Comment by rozhuk-im** [comment]
ReadME!
```git clone --recursive https://github.com/rozhuk-im/msd.git```
Without ```--recursive``` you will not clone https://github.com/rozhuk-im/liblcb
