### ISSUE TITLE
start fail on ubuntu 24.04

### ISSUE THREAD

**Issue by wangmice** [rozhuk-im/msd#4]
the master branch compiled on ubuntu：

Apr 24 12:48:51 msd[1161785]: tpt_data_init() - threads. Error 22: Invalid argument
Apr 24 12:48:51 msd[1161785]: tp_create(). Error 22: Invalid argument
Apr 24 12:48:51 systemd[1]: msd.service: Main process exited, code=exited, status=22/n/a
Apr 24 12:48:51 systemd[1]: msd.service: Failed with result 'exit-code'.

**Comment by rozhuk-im** [comment]
Now should build and run, please check.
