### ISSUE TITLE
Please make docker packages for armv7/arm64/amd64

### ISSUE THREAD

**Issue by vuducdong** [rozhuk-im/msd#5]
Please make docker packages for armv7/arm64/amd64

@rozhuk-im 

Thanks!

**Comment by rozhuk-im** [comment]
There is only source based distribution in this project.

Docker image does not make sense (IMHO):
- there is no extra run time deps - any container will have negative profit by resources usage and administration;
- multicast required in most use cases - extra network setup will be required.
